version: '3.3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE= university_db
  rest-service-book-api:
    image: alb3rtsk21/rest-service:v1
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST= db
      - MYSQL_PORT= 3306
    depends_on:
      - db