spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:}
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/university_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
#    defer-datasource-initialization: true
    open-in-view: false

server:
  port: 8080