spring:
  datasource:
    username: root
    password: Albert.nustiu.2002
    url: jdbc:mysql://localhost:3306/unit_testing_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update